spring.application.name=scm
server.port=8091

spring.datasource.url=jdbc:mysql://localhost:3306/scms
spring.datasource.username=root
spring.datasource.password=1234
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL8Dialect


#oauth2 client configurations
#google configure
spring.security.oauth2.client.registration.google.client-name=google
spring.security.oauth2.client.registration.google.client-id= ${client-id}
spring.security.oauth2.client.registration.google.client-secret=${client-secret}
spring.security.oauth2.client.registration.google.scope=email,profile



#Cloudinary Configuration
Cloudinary.cloud.name=${clud-name}
Cloudinary.api.key=${api-key}
Cloudinary.api.secret=${api-secret}


